DominoKit/domino-ui

src/main/java/org/dominokit/domino/ui/forms/SuggestBox.java
This is especially for using the SuggestBox in a clean MVP manner and
maybe it is also usefull when using templates.
=> Add capability to add SuggestBoxStore after creation of SuggestBox

domino-ui/src/main/java/org/dominokit/domino/ui/lists/ListGroup.java, domino-ui/src/main/java/org/dominokit/domino/ui/lists/ListItem.java
Enhancements for adding and creating ListItems at a ListGroup
=> Enhancements for adding and creating ListItems at a ListGroup

domino-ui/src/main/java/org/dominokit/domino/ui/style/Color.java, domino-ui/src/main/resources/org/dominokit/domino/ui/public/css/colors.css
according to material design color layout, as defined here https://material.io/design/color/the-color-system.html#tools-for-picking-colors, some color values are wrong.
=> fixed material design colors

domino-ui/src/main/java/org/dominokit/domino/ui/pagination/AdvancedPagination.java
Hi, to make the Advanced Pagination accessible, I added key events to the anchors and made them tabbable.
Regards
=> Accessibility - Advanced Pagination

domino-ui/src/main/java/org/dominokit/domino/ui/breadcrumbs/BreadcrumbItem.java
Hi, to make the breadcrumb accessible, I made anchor of BreadcrumbItem tabbable.
Regards.
=> Accessibility - Breadcrumb

domino-ui/src/main/java/org/dominokit/domino/ui/forms/CheckBox.java
Hi, to make the checkbox accessible, I added key events to the inputElement of checkbox.
Regards.
=> Accessibility - checkbox

domino-ui/src/main/resources/org/dominokit/domino/ui/public/css/button/button.css
=> add small size to circle button

domino-ui/src/main/java/org/dominokit/domino/ui/layout/NavigationBar.java
new getter for actionBarItem and titleItem to have the possibilty to modify its styling attributes programmatically.
=> getter for actionBarItem and titleItem

domino-ui/src/main/java/org/dominokit/domino/ui/chips/ChipsGroup.java
DeSelectionHandler for the chip group
=> DeSelectionHandler for the chip group

domino-ui/src/main/java/org/dominokit/domino/ui/modals/BaseModal.java
Instead of for every keypress.
This fixes https://github.com/DominoKit/domino-ui/issues/462
=> ModalBase only updates focuselement on "Tab" keypress

domino-ui/src/main/java/org/dominokit/domino/ui/timepicker/Clock.java, domino-ui/src/main/java/org/dominokit/domino/ui/timepicker/Clock12.java, domino-ui/src/main/java/org/dominokit/domino/ui/timepicker/Clock24.java, domino-ui/src/main/java/org/dominokit/domino/ui/timepicker/ClockElement.java, domino-ui/src/main/java/org/dominokit/domino/ui/timepicker/TimePicker.java, domino-ui/src/main/java/org/dominokit/domino/ui/timepicker/TimePickerStyles.java, domino-ui/src/main/resources/org/dominokit/domino/ui/public/css/timepicker/timepicker.css
Fix for https://github.com/DominoKit/domino-ui/issues/379
=> Enhance the TimeBox with a possibility to set also seconds.

domino-ui/src/main/java/org/dominokit/domino/ui/progress/ProgressBar.java
=> Implemented setMaxValue on ProgressBar

domino-ui/src/main/java/org/dominokit/domino/ui/upload/FileItem.java
=> change threshold value

domino-ui/src/main/java/org/dominokit/domino/ui/datatable/DataTable.java, domino-ui/src/main/java/org/dominokit/domino/ui/datatable/DataTableStyles.java, domino-ui/src/main/resources/org/dominokit/domino/ui/public/css/datatable/datatable.css
+ added percentage column width support
ideas from:
* [scroll fix](https://stackoverflow.com/questions/14977864/fixed-header-table-with-horizontal-scrollbar-and-vertical-scrollbar-on) 
* [percentage](https://stackoverflow.com/questions/23989463/how-to-set-tbody-height-with-overflow-scroll)
=> fix #316. DataTable scrollbar issues resolution

domino-ui/src/main/resources/org/dominokit/domino/ui/public/css/datatable/datatable.css
in my prev. PR for table scrolling i'm broke ellipsis drawing in table cells when text longer than cell width :(
=> fix: #316. fixing ellipsis issue in fixed table cells

domino-ui/src/main/java/org/dominokit/domino/ui/dropdown/DropDownMenu.java, domino-ui/src/main/java/org/dominokit/domino/ui/forms/AbstractSelect.java
As discussed at https://github.com/DominoKit/domino-ui/issues/350 a select  has now the possibility to create new entries.
=> https://github.com/DominoKit/domino-ui/issues/350

domino-ui/src/main/java/org/dominokit/domino/ui/dropdown/DropDownMenu.java
setter for NoMatchSearchResultText to have the possibility to localize the text
=> setter for NoMatchSearchResultText

domino-ui/src/main/java/org/dominokit/domino/ui/forms/AbstractSuggestBox.java, domino-ui/src/main/java/org/dominokit/domino/ui/forms/DominoFields.java
* fix dropdown direction calc (in Your code some logic broken- wrong distance calculation and popup prefers drop to up) 
* added posibility specify maximal dropdown width (when unset - limits to suggestbox width)
=> SuggestBox popup enchancements

domino-ui/src/main/java/org/dominokit/domino/ui/forms/CheckBox.java
=> checkbox ReadOnly label not changed when setted new label

domino-ui/src/main/java/org/dominokit/domino/ui/datepicker/DateBox.java
improve datebox set pattern, so a pattern change will be pushed to input element value.
also update the private setStringValue method, it only updates the input value.
=> ticket 538, improve datebox set pattern

domino-ui/src/main/java/org/dominokit/domino/ui/forms/NumberBox.java
fix NPE when clearing min/max/step values in NumberBox
=> fix null passing to NumberBox.setMaxValue/setMinValue/setStep

domino-ui/src/main/java/org/dominokit/domino/ui/forms/Select.java
may be more correct behaviour clear value when set any value not presented in available options, but this is terms for discussions
but when NULL passed control must be cleared anyway ;-)
=> Select not cleared when setValue(null) passed

domino-ui/src/main/java/org/dominokit/domino/ui/forms/LocalSuggestBoxStore.java
wrong null check in `LocalSuggestBoxStore.getMessingSuggestionProvider` (wrong field checked)
=> small copy-paste fix

domino-ui/src/main/java/org/dominokit/domino/ui/tag/AbstractTagsInput.java, domino-ui/src/main/java/org/dominokit/domino/ui/tag/TagsInput.java
and few small enchancements:
* added get/setTagStore
* ability call setValue(null) 
* reenable/disable when setMaxValue called (not only on setValue)
=> AbstractTagsInput extracted

domino-ui/src/main/java/org/dominokit/domino/ui/tag/AbstractTagsInput.java
as example try focus from tagsinput with opened dropdown to another tagsinput in demo
=> Opened dropdowns not closed when focused to tagsinput

domino-ui/src/main/java/org/dominokit/domino/ui/upload/FileItem.java
* fix tooltip when message changed
* make isExceedsMaxFile public
=> Small FileUpload fixes

domino-ui/src/main/java/org/dominokit/domino/ui/tabs/TabsPanel.java
Possible to reuse find key part in the original activateByKey method.
=> extract find code part from activateByKey
