DominoKit/domino-ui

- src/main/java/org/dominokit/domino/ui/collapsible/Accordion.java
The panels should be exposed, so one can loop through all panels.
> Expose the panels from the Accordion.

- domino-ui/src/main/java/org/dominokit/domino/ui/lists/BaseListItem.java
- domino-ui/src/main/java/org/dominokit/domino/ui/lists/SimpleListItem.java
On simple list items the label is wrapped correctly when adding badges on list items not. So this PR moves the logic to deal with badges from simple list to base class.
> Move badge logic to base class to support all lists

- domino-ui/src/main/java/org/dominokit/domino/ui/upload/FileItem.java
Response text can be readed when response type is empty string or "text".
See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseText
Fix #320
> Take care of response type reading response text

- domino-ui/src/main/java/org/dominokit/domino/ui/upload/FileUpload.java
- domino-ui/src/main/resources/org/dominokit/domino/ui/public/css/style.css
Only consider the "dragleave" event when leaving the main area of the file upload.
Fix for #345 and keep pointer events disabled
> Eventleave iexplorer problem

- domino-ui-tools/mdi-icons-processor/pom.xml
See https://github.com/google/auto/tree/master/common#processor-resilience
The basic idea is to keep the apt jar as simple as possible, and
avoid external depenencies or classes that might conflict on the
classpath of the code being compiles with this processor. On Gradle
or some other build tool we can rely on classpaths not getting mixed,
but it is riskier in maevn, so we need to take care not to have
some library version in this processor break another processor or
vice versa, or to have some dependency here force another library
to be updated or vice versa.
> Simplify apt jar and dependencies.

- domino-ui/src/main/java/org/dominokit/domino/ui/dialogs/ConfirmationDialog.java
Reduce the amount of implementations of the reject handler each time the dialog should just closed on cancelation.
> Default behavior for the reject handler

- domino-ui-tools/mdi-icons-processor/pom.xml
Almost certainly this isn't actually necessary since this processor is unlikely to be used outside of this project, but trying to keep things as clean as possible so that we don't get surprises later.
> Relocate a few classes and stop trying to take over java packages

- domino-ui-shared/pom.xml
I understand that j2cl should never actually need these classes, but in order to strip and transpile domino-ui.jar the way that the maven plugin does it today, we have to have these one way or another. Since the jar is so tiny, I don't think adding sources is an issue?
> Include shared sources in jar so j2cl can handle it

- domino-ui/src/main/java/org/dominokit/domino/ui/forms/NumberBox.java
Calling `BigDecimalBox.validate().isValid()` on an input field, that contains an illegal token (NaN) will return true - which is, in this case, definitiv wrong.
This PR adds another validation to the `NumberBox` super class which checks if an illegal token is entered.
> Fixed an issue with validate().isValid() and illegal Token in NumberBox

- domino-ui/src/main/java/org/dominokit/domino/ui/datepicker/DateBox.java
You can now call setParseStrict(true) to enable parseStrict to be used for the Formatter.
Default behaviour is normal parse, like beore
> Added option to parseStrict to DateBox

- domino-ui/src/main/java/org/dominokit/domino/ui/keyboard/KeyboardEvents.java
Probably result of a browser bug.
Closes #436.
> Ignore keyboard events without keycode

- domino-ui/src/main/java/org/dominokit/domino/ui/splitpanel/BaseSplitPanel.java
- domino-ui/src/main/java/org/dominokit/domino/ui/splitpanel/BaseSplitter.java
- domino-ui/src/main/java/org/dominokit/domino/ui/splitpanel/HSplitter.java
- domino-ui/src/main/java/org/dominokit/domino/ui/splitpanel/HasSize.java
- domino-ui/src/main/java/org/dominokit/domino/ui/splitpanel/SplitPanel.java
- domino-ui/src/main/java/org/dominokit/domino/ui/splitpanel/VSplitter.java
There is an issue with split panel sizes, e.g. when creating a 50%:50% split, the HSplitter is not centered in the middle of the main panel container on page init. 
Further, when resizing a horizontal split panel whose main panel is 100% percent wide and resizing the browser window afterwards, the computed width percentages may not fit anymore for the given splitterSize resulting in rendering issues for the content. 
The provided approach here simplifies the computation of sizes, as it always uses overall percentages and substracts the splitterSizes afterwards.
> improved split panel size adjustment

- domino-ui/src/main/java/org/dominokit/domino/ui/notifications/Notification.java
* moved all global initialization from `create()` to constructor
* added `setType(String)` for changing type after class is constructed
These modifications make extending `Notification` class possible without duplicating code from `Notification.create()`. Apps can extend `Notification` and apply their own defaults (style, position, ...).
> Make Notification easier to extend

- domino-ui/src/main/java/org/dominokit/domino/ui/utils/BaseDominoElement.java
Although using `BaseDominoElement.getTooltip().detach()` we can remove existing tooltip, without null-ing `BaseDominoElement.tooltip` member it's impossible to set tooltip again later if required.
`BaseDominoElement.removeTooltip()` does (checked) cleanup if tooltip was set and prepares state to set it again.
> BaseDominoElement.removeTooltip

- domino-ui/src/main/java/org/dominokit/domino/ui/tree/Tree.java
- domino-ui/src/main/java/org/dominokit/domino/ui/tree/TreeItem.java
in your code padding for tree levels hardcoded in sources. i move padding to css and remove unneeded code.
in result - padding can be easy configured
i tests with dominoui-demo and my own project, all works same except two small things:
* in your code first level has extra 15px padding (you leveling from 1st level instead 0). I think in my variant more correct behaviour, but if You want i can add extra padding for first level (via css).
* in my code  separarator lines also padded left to level. I dont know how change this for prev behaviour, but i also think: its looks more elegant ;-)
> move tree leveling from code to css

- domino-ui/src/main/java/org/dominokit/domino/ui/forms/CheckBox.java
set label by removing local label variable, otherwise set label again does not have ui effect on a readonly checkbox, which has already a value set.
```
CheckBox checkBox = CheckBox.create("old label").setReadOnly(true);
checkBox.setLabel("new label");
// setValue is here needed to show the current bug.
checkBox.setValue(true);
DomGlobal.document.body.appendChild(checkBox.element());
```
> improve check box set label

- domino-ui/src/main/java/org/dominokit/domino/ui/forms/ValueBox.java
example:
valueBox.setReadOnly(true).setReadOnly(false) - and label floating always
> fix label floating after setReadOnly called with true and false

- domino-ui/src/main/java/org/dominokit/domino/ui/public/polyfill/polyfill-ie11.js
At least in new Chrome polyfill shows error:
```
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(...) is not a function
at polyfill-ie11.js:68:2
```
i don't see this before, but propose small fix ;-)
i found solution in https://stackoverflow.com/questions/42036349/uncaught-typeerror-intermediate-value-is-not-a-function
> fix polyfill Type error message

- domino-ui/src/main/java/org/dominokit/domino/ui/datatable/plugins/GroupingPlugin.java
make `getDataGroups` method and `DataGroup` class public
move cell content rendering code to `DataGroup` (`render` method)
this makes possibility re-render group cell if needed ;-)
> DataTable GroupingPlugin improvements

- domino-ui/src/main/java/org/dominokit/domino/ui/datatable/DataTable.java
- domino-ui/src/main/java/org/dominokit/domino/ui/datatable/TableRow.java
- domino-ui/src/main/java/org/dominokit/domino/ui/datatable/plugins/GroupingPlugin.java
* add public DataTable.getDataStore method
* add public TableRow.getDataTable method
* implements RowMetaObject in DataGroup and add MetaObject with corresponding DataGroup to TableRow. 
* add static method DataGroup.fromRow. example usage (in grid editor onchange ): 
```
DataGroup.fromRow(cell.getTableRow()).render();
```
> DataTable & Grouping plugin improvements

- domino-ui/src/main/java/org/dominokit/domino/ui/breadcrumbs/Breadcrumb.java
- domino-ui/src/main/java/org/dominokit/domino/ui/breadcrumbs/BreadcrumbItem.java
1) Add removeChildFrom method, which allows you reset a Breadcrumb from a certain child.
2) Since removeChildFrom method is added, in method addNewItems, setActiveItem should be called on the last index of this.items, not items.
3) Change LinkedList to ArrayList for better random access on child items, do not see any reason why LinkedList is used before.
4) Breadcrumb is featured with HasChangeHandlers, to notify any active BreadcrumbItem change, before there is no way to detect it.
5) Due to new HasChangeHandlers feature:
a) setActive method in Breadcrumb is public now
b) setActive method in BreadcrumbItem deprecated, since you should call via the Breadcrumb to notify changeHandlers.
c) active and deActive in BreadcrumbItem are protected now, they should being called only from …
> Breadcrumb enhancement
